/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsAmlScreeningRouteImport } from './routes/solutions.aml-screening'
import { Route as SolutionsBusinessVerificationRouteImport } from './routes/solutions.business-verification'
import { Route as SolutionsFraudRiskRouteImport } from './routes/solutions.fraud-risk'
import { Route as SolutionsPersonVerificationRouteImport } from './routes/solutions.person-verification'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminOwnerRouteImport } from './routes/_authenticated/admin.owner'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleAlertsRouteImport } from './routes/_authenticated/console.alerts'
import { Route as AuthenticatedConsoleAuditRouteImport } from './routes/_authenticated/console.audit'
import { Route as AuthenticatedConsoleComplianceRouteImport } from './routes/_authenticated/console.compliance'
import { Route as AuthenticatedConsoleGoLiveRouteImport } from './routes/_authenticated/console.go-live'
import { Route as AuthenticatedConsoleReportsRouteImport } from './routes/_authenticated/console.reports'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console.settings'
import { Route as AuthenticatedConsoleTransactionsRouteImport } from './routes/_authenticated/console.transactions'
import { Route as AuthenticatedConsoleWatchlistsRouteImport } from './routes/_authenticated/console.watchlists'
import { Route as AuthenticatedAdminCompaniesOrgIdRouteImport } from './routes/_authenticated/admin.companies.$orgId'
import { Route as AuthenticatedAdminInvoicesInvoiceIdRouteImport } from './routes/_authenticated/admin.invoices.$invoiceId'
import { Route as AuthenticatedConsoleCasesCaseIdRouteImport } from './routes/_authenticated/console.cases.$caseId'
import { Route as ApiPublicHooksPlaidSyncRouteImport } from './routes/api/public/hooks/plaid-sync'
import { Route as ApiPublicHooksRefreshWatchlistsRouteImport } from './routes/api/public/hooks/refresh-watchlists'
import { Route as ApiPublicHooksRescreenRouteImport } from './routes/api/public/hooks/rescreen'
import { Route as ApiPublicV1AlertsRouteImport } from './routes/api/public/v1/alerts'
import { Route as ApiPublicV1CasesRouteImport } from './routes/api/public/v1/cases'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1ReportsRouteImport } from './routes/api/public/v1/reports'
import { Route as ApiPublicV1ScreeningRouteImport } from './routes/api/public/v1/screening'
import { Route as ApiPublicV1TransactionsRouteImport } from './routes/api/public/v1/transactions'
import { Route as ApiPublicV1AlertsAlertIdRouteImport } from './routes/api/public/v1/alerts.$alertId'
import { Route as ApiPublicV1CasesCaseIdRouteImport } from './routes/api/public/v1/cases.$caseId'
import { Route as ApiPublicV1HitsHitIdRouteImport } from './routes/api/public/v1/hits.$hitId'
import { Route as ApiPublicV1HostedTokenRouteImport } from './routes/api/public/v1/hosted.$token'
import { Route as ApiPublicV1ReportsReportIdRouteImport } from './routes/api/public/v1/reports.$reportId'
import { Route as ApiPublicV1CasesCaseIdAddressesRouteImport } from './routes/api/public/v1/cases.$caseId.addresses'
import { Route as ApiPublicV1CasesCaseIdBankRouteImport } from './routes/api/public/v1/cases.$caseId.bank'
import { Route as ApiPublicV1CasesCaseIdDecisionRouteImport } from './routes/api/public/v1/cases.$caseId.decision'
import { Route as ApiPublicV1CasesCaseIdDocumentsRouteImport } from './routes/api/public/v1/cases.$caseId.documents'
import { Route as ApiPublicV1CasesCaseIdHitsRouteImport } from './routes/api/public/v1/cases.$caseId.hits'
import { Route as ApiPublicV1CasesCaseIdOwnersRouteImport } from './routes/api/public/v1/cases.$caseId.owners'
import { Route as ApiPublicV1CasesCaseIdOwnershipRouteImport } from './routes/api/public/v1/cases.$caseId.ownership'
import { Route as ApiPublicV1CasesCaseIdRiskRouteImport } from './routes/api/public/v1/cases.$caseId.risk'
import { Route as ApiPublicV1CasesCaseIdScreenRouteImport } from './routes/api/public/v1/cases.$caseId.screen'
import { Route as ApiPublicV1CasesCaseIdSelfiesRouteImport } from './routes/api/public/v1/cases.$caseId.selfies'
import { Route as ApiPublicV1CasesCaseIdVerificationSessionsRouteImport } from './routes/api/public/v1/cases.$caseId.verification-sessions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAmlScreeningRoute = SolutionsAmlScreeningRouteImport.update({
  id: '/solutions/aml-screening',
  path: '/solutions/aml-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBusinessVerificationRoute =
  SolutionsBusinessVerificationRouteImport.update({
    id: '/solutions/business-verification',
    path: '/solutions/business-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsFraudRiskRoute = SolutionsFraudRiskRouteImport.update({
  id: '/solutions/fraud-risk',
  path: '/solutions/fraud-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPersonVerificationRoute =
  SolutionsPersonVerificationRouteImport.update({
    id: '/solutions/person-verification',
    path: '/solutions/person-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOwnerRoute = AuthenticatedAdminOwnerRouteImport.update({
  id: '/admin/owner',
  path: '/admin/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/console/',
    path: '/console/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleAlertsRoute =
  AuthenticatedConsoleAlertsRouteImport.update({
    id: '/console/alerts',
    path: '/console/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleAuditRoute =
  AuthenticatedConsoleAuditRouteImport.update({
    id: '/console/audit',
    path: '/console/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleComplianceRoute =
  AuthenticatedConsoleComplianceRouteImport.update({
    id: '/console/compliance',
    path: '/console/compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleGoLiveRoute =
  AuthenticatedConsoleGoLiveRouteImport.update({
    id: '/console/go-live',
    path: '/console/go-live',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleReportsRoute =
  AuthenticatedConsoleReportsRouteImport.update({
    id: '/console/reports',
    path: '/console/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/console/settings',
    path: '/console/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleTransactionsRoute =
  AuthenticatedConsoleTransactionsRouteImport.update({
    id: '/console/transactions',
    path: '/console/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleWatchlistsRoute =
  AuthenticatedConsoleWatchlistsRouteImport.update({
    id: '/console/watchlists',
    path: '/console/watchlists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesOrgIdRoute =
  AuthenticatedAdminCompaniesOrgIdRouteImport.update({
    id: '/admin/companies/$orgId',
    path: '/admin/companies/$orgId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesInvoiceIdRoute =
  AuthenticatedAdminInvoicesInvoiceIdRouteImport.update({
    id: '/admin/invoices/$invoiceId',
    path: '/admin/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleCasesCaseIdRoute =
  AuthenticatedConsoleCasesCaseIdRouteImport.update({
    id: '/console/cases/$caseId',
    path: '/console/cases/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPlaidSyncRoute = ApiPublicHooksPlaidSyncRouteImport.update({
  id: '/api/public/hooks/plaid-sync',
  path: '/api/public/hooks/plaid-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshWatchlistsRoute =
  ApiPublicHooksRefreshWatchlistsRouteImport.update({
    id: '/api/public/hooks/refresh-watchlists',
    path: '/api/public/hooks/refresh-watchlists',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRescreenRoute = ApiPublicHooksRescreenRouteImport.update({
  id: '/api/public/hooks/rescreen',
  path: '/api/public/hooks/rescreen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AlertsRoute = ApiPublicV1AlertsRouteImport.update({
  id: '/api/public/v1/alerts',
  path: '/api/public/v1/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CasesRoute = ApiPublicV1CasesRouteImport.update({
  id: '/api/public/v1/cases',
  path: '/api/public/v1/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReportsRoute = ApiPublicV1ReportsRouteImport.update({
  id: '/api/public/v1/reports',
  path: '/api/public/v1/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ScreeningRoute = ApiPublicV1ScreeningRouteImport.update({
  id: '/api/public/v1/screening',
  path: '/api/public/v1/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TransactionsRoute = ApiPublicV1TransactionsRouteImport.update({
  id: '/api/public/v1/transactions',
  path: '/api/public/v1/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AlertsAlertIdRoute =
  ApiPublicV1AlertsAlertIdRouteImport.update({
    id: '/$alertId',
    path: '/$alertId',
    getParentRoute: () => ApiPublicV1AlertsRoute,
  } as any)
const ApiPublicV1CasesCaseIdRoute = ApiPublicV1CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ApiPublicV1CasesRoute,
} as any)
const ApiPublicV1HitsHitIdRoute = ApiPublicV1HitsHitIdRouteImport.update({
  id: '/api/public/v1/hits/$hitId',
  path: '/api/public/v1/hits/$hitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HostedTokenRoute = ApiPublicV1HostedTokenRouteImport.update({
  id: '/api/public/v1/hosted/$token',
  path: '/api/public/v1/hosted/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReportsReportIdRoute =
  ApiPublicV1ReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => ApiPublicV1ReportsRoute,
  } as any)
const ApiPublicV1CasesCaseIdAddressesRoute =
  ApiPublicV1CasesCaseIdAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdBankRoute =
  ApiPublicV1CasesCaseIdBankRouteImport.update({
    id: '/bank',
    path: '/bank',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdDecisionRoute =
  ApiPublicV1CasesCaseIdDecisionRouteImport.update({
    id: '/decision',
    path: '/decision',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdDocumentsRoute =
  ApiPublicV1CasesCaseIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdHitsRoute =
  ApiPublicV1CasesCaseIdHitsRouteImport.update({
    id: '/hits',
    path: '/hits',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdOwnersRoute =
  ApiPublicV1CasesCaseIdOwnersRouteImport.update({
    id: '/owners',
    path: '/owners',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdOwnershipRoute =
  ApiPublicV1CasesCaseIdOwnershipRouteImport.update({
    id: '/ownership',
    path: '/ownership',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdRiskRoute =
  ApiPublicV1CasesCaseIdRiskRouteImport.update({
    id: '/risk',
    path: '/risk',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdScreenRoute =
  ApiPublicV1CasesCaseIdScreenRouteImport.update({
    id: '/screen',
    path: '/screen',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdSelfiesRoute =
  ApiPublicV1CasesCaseIdSelfiesRouteImport.update({
    id: '/selfies',
    path: '/selfies',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)
const ApiPublicV1CasesCaseIdVerificationSessionsRoute =
  ApiPublicV1CasesCaseIdVerificationSessionsRouteImport.update({
    id: '/verification-sessions',
    path: '/verification-sessions',
    getParentRoute: () => ApiPublicV1CasesCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/solutions/aml-screening': typeof SolutionsAmlScreeningRoute
  '/solutions/business-verification': typeof SolutionsBusinessVerificationRoute
  '/solutions/fraud-risk': typeof SolutionsFraudRiskRoute
  '/solutions/person-verification': typeof SolutionsPersonVerificationRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/owner': typeof AuthenticatedAdminOwnerRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/console/alerts': typeof AuthenticatedConsoleAlertsRoute
  '/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/console/compliance': typeof AuthenticatedConsoleComplianceRoute
  '/console/go-live': typeof AuthenticatedConsoleGoLiveRoute
  '/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/console/watchlists': typeof AuthenticatedConsoleWatchlistsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/admin/companies/$orgId': typeof AuthenticatedAdminCompaniesOrgIdRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/console/cases/$caseId': typeof AuthenticatedConsoleCasesCaseIdRoute
  '/api/public/hooks/plaid-sync': typeof ApiPublicHooksPlaidSyncRoute
  '/api/public/hooks/refresh-watchlists': typeof ApiPublicHooksRefreshWatchlistsRoute
  '/api/public/hooks/rescreen': typeof ApiPublicHooksRescreenRoute
  '/api/public/v1/alerts': typeof ApiPublicV1AlertsRouteWithChildren
  '/api/public/v1/cases': typeof ApiPublicV1CasesRouteWithChildren
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/reports': typeof ApiPublicV1ReportsRouteWithChildren
  '/api/public/v1/screening': typeof ApiPublicV1ScreeningRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
  '/api/public/v1/alerts/$alertId': typeof ApiPublicV1AlertsAlertIdRoute
  '/api/public/v1/cases/$caseId': typeof ApiPublicV1CasesCaseIdRouteWithChildren
  '/api/public/v1/hits/$hitId': typeof ApiPublicV1HitsHitIdRoute
  '/api/public/v1/hosted/$token': typeof ApiPublicV1HostedTokenRoute
  '/api/public/v1/reports/$reportId': typeof ApiPublicV1ReportsReportIdRoute
  '/api/public/v1/cases/$caseId/addresses': typeof ApiPublicV1CasesCaseIdAddressesRoute
  '/api/public/v1/cases/$caseId/bank': typeof ApiPublicV1CasesCaseIdBankRoute
  '/api/public/v1/cases/$caseId/decision': typeof ApiPublicV1CasesCaseIdDecisionRoute
  '/api/public/v1/cases/$caseId/documents': typeof ApiPublicV1CasesCaseIdDocumentsRoute
  '/api/public/v1/cases/$caseId/hits': typeof ApiPublicV1CasesCaseIdHitsRoute
  '/api/public/v1/cases/$caseId/owners': typeof ApiPublicV1CasesCaseIdOwnersRoute
  '/api/public/v1/cases/$caseId/ownership': typeof ApiPublicV1CasesCaseIdOwnershipRoute
  '/api/public/v1/cases/$caseId/risk': typeof ApiPublicV1CasesCaseIdRiskRoute
  '/api/public/v1/cases/$caseId/screen': typeof ApiPublicV1CasesCaseIdScreenRoute
  '/api/public/v1/cases/$caseId/selfies': typeof ApiPublicV1CasesCaseIdSelfiesRoute
  '/api/public/v1/cases/$caseId/verification-sessions': typeof ApiPublicV1CasesCaseIdVerificationSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/solutions/aml-screening': typeof SolutionsAmlScreeningRoute
  '/solutions/business-verification': typeof SolutionsBusinessVerificationRoute
  '/solutions/fraud-risk': typeof SolutionsFraudRiskRoute
  '/solutions/person-verification': typeof SolutionsPersonVerificationRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/solutions': typeof SolutionsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/owner': typeof AuthenticatedAdminOwnerRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/console/alerts': typeof AuthenticatedConsoleAlertsRoute
  '/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/console/compliance': typeof AuthenticatedConsoleComplianceRoute
  '/console/go-live': typeof AuthenticatedConsoleGoLiveRoute
  '/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/console/watchlists': typeof AuthenticatedConsoleWatchlistsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/admin/companies/$orgId': typeof AuthenticatedAdminCompaniesOrgIdRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/console/cases/$caseId': typeof AuthenticatedConsoleCasesCaseIdRoute
  '/api/public/hooks/plaid-sync': typeof ApiPublicHooksPlaidSyncRoute
  '/api/public/hooks/refresh-watchlists': typeof ApiPublicHooksRefreshWatchlistsRoute
  '/api/public/hooks/rescreen': typeof ApiPublicHooksRescreenRoute
  '/api/public/v1/alerts': typeof ApiPublicV1AlertsRouteWithChildren
  '/api/public/v1/cases': typeof ApiPublicV1CasesRouteWithChildren
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/reports': typeof ApiPublicV1ReportsRouteWithChildren
  '/api/public/v1/screening': typeof ApiPublicV1ScreeningRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
  '/api/public/v1/alerts/$alertId': typeof ApiPublicV1AlertsAlertIdRoute
  '/api/public/v1/cases/$caseId': typeof ApiPublicV1CasesCaseIdRouteWithChildren
  '/api/public/v1/hits/$hitId': typeof ApiPublicV1HitsHitIdRoute
  '/api/public/v1/hosted/$token': typeof ApiPublicV1HostedTokenRoute
  '/api/public/v1/reports/$reportId': typeof ApiPublicV1ReportsReportIdRoute
  '/api/public/v1/cases/$caseId/addresses': typeof ApiPublicV1CasesCaseIdAddressesRoute
  '/api/public/v1/cases/$caseId/bank': typeof ApiPublicV1CasesCaseIdBankRoute
  '/api/public/v1/cases/$caseId/decision': typeof ApiPublicV1CasesCaseIdDecisionRoute
  '/api/public/v1/cases/$caseId/documents': typeof ApiPublicV1CasesCaseIdDocumentsRoute
  '/api/public/v1/cases/$caseId/hits': typeof ApiPublicV1CasesCaseIdHitsRoute
  '/api/public/v1/cases/$caseId/owners': typeof ApiPublicV1CasesCaseIdOwnersRoute
  '/api/public/v1/cases/$caseId/ownership': typeof ApiPublicV1CasesCaseIdOwnershipRoute
  '/api/public/v1/cases/$caseId/risk': typeof ApiPublicV1CasesCaseIdRiskRoute
  '/api/public/v1/cases/$caseId/screen': typeof ApiPublicV1CasesCaseIdScreenRoute
  '/api/public/v1/cases/$caseId/selfies': typeof ApiPublicV1CasesCaseIdSelfiesRoute
  '/api/public/v1/cases/$caseId/verification-sessions': typeof ApiPublicV1CasesCaseIdVerificationSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/solutions/aml-screening': typeof SolutionsAmlScreeningRoute
  '/solutions/business-verification': typeof SolutionsBusinessVerificationRoute
  '/solutions/fraud-risk': typeof SolutionsFraudRiskRoute
  '/solutions/person-verification': typeof SolutionsPersonVerificationRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/owner': typeof AuthenticatedAdminOwnerRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/console/alerts': typeof AuthenticatedConsoleAlertsRoute
  '/_authenticated/console/audit': typeof AuthenticatedConsoleAuditRoute
  '/_authenticated/console/compliance': typeof AuthenticatedConsoleComplianceRoute
  '/_authenticated/console/go-live': typeof AuthenticatedConsoleGoLiveRoute
  '/_authenticated/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/_authenticated/console/transactions': typeof AuthenticatedConsoleTransactionsRoute
  '/_authenticated/console/watchlists': typeof AuthenticatedConsoleWatchlistsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/admin/companies/$orgId': typeof AuthenticatedAdminCompaniesOrgIdRoute
  '/_authenticated/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/_authenticated/console/cases/$caseId': typeof AuthenticatedConsoleCasesCaseIdRoute
  '/api/public/hooks/plaid-sync': typeof ApiPublicHooksPlaidSyncRoute
  '/api/public/hooks/refresh-watchlists': typeof ApiPublicHooksRefreshWatchlistsRoute
  '/api/public/hooks/rescreen': typeof ApiPublicHooksRescreenRoute
  '/api/public/v1/alerts': typeof ApiPublicV1AlertsRouteWithChildren
  '/api/public/v1/cases': typeof ApiPublicV1CasesRouteWithChildren
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/reports': typeof ApiPublicV1ReportsRouteWithChildren
  '/api/public/v1/screening': typeof ApiPublicV1ScreeningRoute
  '/api/public/v1/transactions': typeof ApiPublicV1TransactionsRoute
  '/api/public/v1/alerts/$alertId': typeof ApiPublicV1AlertsAlertIdRoute
  '/api/public/v1/cases/$caseId': typeof ApiPublicV1CasesCaseIdRouteWithChildren
  '/api/public/v1/hits/$hitId': typeof ApiPublicV1HitsHitIdRoute
  '/api/public/v1/hosted/$token': typeof ApiPublicV1HostedTokenRoute
  '/api/public/v1/reports/$reportId': typeof ApiPublicV1ReportsReportIdRoute
  '/api/public/v1/cases/$caseId/addresses': typeof ApiPublicV1CasesCaseIdAddressesRoute
  '/api/public/v1/cases/$caseId/bank': typeof ApiPublicV1CasesCaseIdBankRoute
  '/api/public/v1/cases/$caseId/decision': typeof ApiPublicV1CasesCaseIdDecisionRoute
  '/api/public/v1/cases/$caseId/documents': typeof ApiPublicV1CasesCaseIdDocumentsRoute
  '/api/public/v1/cases/$caseId/hits': typeof ApiPublicV1CasesCaseIdHitsRoute
  '/api/public/v1/cases/$caseId/owners': typeof ApiPublicV1CasesCaseIdOwnersRoute
  '/api/public/v1/cases/$caseId/ownership': typeof ApiPublicV1CasesCaseIdOwnershipRoute
  '/api/public/v1/cases/$caseId/risk': typeof ApiPublicV1CasesCaseIdRiskRoute
  '/api/public/v1/cases/$caseId/screen': typeof ApiPublicV1CasesCaseIdScreenRoute
  '/api/public/v1/cases/$caseId/selfies': typeof ApiPublicV1CasesCaseIdSelfiesRoute
  '/api/public/v1/cases/$caseId/verification-sessions': typeof ApiPublicV1CasesCaseIdVerificationSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/pricing'
    | '/onboarding'
    | '/invite/$token'
    | '/solutions/aml-screening'
    | '/solutions/business-verification'
    | '/solutions/fraud-risk'
    | '/solutions/person-verification'
    | '/verify/$token'
    | '/solutions/'
    | '/admin/applications'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/integrations'
    | '/admin/owner'
    | '/admin/plans'
    | '/console/alerts'
    | '/console/audit'
    | '/console/compliance'
    | '/console/go-live'
    | '/console/reports'
    | '/console/settings'
    | '/console/transactions'
    | '/console/watchlists'
    | '/admin/'
    | '/console/'
    | '/admin/companies/$orgId'
    | '/admin/invoices/$invoiceId'
    | '/console/cases/$caseId'
    | '/api/public/hooks/plaid-sync'
    | '/api/public/hooks/refresh-watchlists'
    | '/api/public/hooks/rescreen'
    | '/api/public/v1/alerts'
    | '/api/public/v1/cases'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/ping'
    | '/api/public/v1/reports'
    | '/api/public/v1/screening'
    | '/api/public/v1/transactions'
    | '/api/public/v1/alerts/$alertId'
    | '/api/public/v1/cases/$caseId'
    | '/api/public/v1/hits/$hitId'
    | '/api/public/v1/hosted/$token'
    | '/api/public/v1/reports/$reportId'
    | '/api/public/v1/cases/$caseId/addresses'
    | '/api/public/v1/cases/$caseId/bank'
    | '/api/public/v1/cases/$caseId/decision'
    | '/api/public/v1/cases/$caseId/documents'
    | '/api/public/v1/cases/$caseId/hits'
    | '/api/public/v1/cases/$caseId/owners'
    | '/api/public/v1/cases/$caseId/ownership'
    | '/api/public/v1/cases/$caseId/risk'
    | '/api/public/v1/cases/$caseId/screen'
    | '/api/public/v1/cases/$caseId/selfies'
    | '/api/public/v1/cases/$caseId/verification-sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/pricing'
    | '/onboarding'
    | '/invite/$token'
    | '/solutions/aml-screening'
    | '/solutions/business-verification'
    | '/solutions/fraud-risk'
    | '/solutions/person-verification'
    | '/verify/$token'
    | '/solutions'
    | '/admin/applications'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/integrations'
    | '/admin/owner'
    | '/admin/plans'
    | '/console/alerts'
    | '/console/audit'
    | '/console/compliance'
    | '/console/go-live'
    | '/console/reports'
    | '/console/settings'
    | '/console/transactions'
    | '/console/watchlists'
    | '/admin'
    | '/console'
    | '/admin/companies/$orgId'
    | '/admin/invoices/$invoiceId'
    | '/console/cases/$caseId'
    | '/api/public/hooks/plaid-sync'
    | '/api/public/hooks/refresh-watchlists'
    | '/api/public/hooks/rescreen'
    | '/api/public/v1/alerts'
    | '/api/public/v1/cases'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/ping'
    | '/api/public/v1/reports'
    | '/api/public/v1/screening'
    | '/api/public/v1/transactions'
    | '/api/public/v1/alerts/$alertId'
    | '/api/public/v1/cases/$caseId'
    | '/api/public/v1/hits/$hitId'
    | '/api/public/v1/hosted/$token'
    | '/api/public/v1/reports/$reportId'
    | '/api/public/v1/cases/$caseId/addresses'
    | '/api/public/v1/cases/$caseId/bank'
    | '/api/public/v1/cases/$caseId/decision'
    | '/api/public/v1/cases/$caseId/documents'
    | '/api/public/v1/cases/$caseId/hits'
    | '/api/public/v1/cases/$caseId/owners'
    | '/api/public/v1/cases/$caseId/ownership'
    | '/api/public/v1/cases/$caseId/risk'
    | '/api/public/v1/cases/$caseId/screen'
    | '/api/public/v1/cases/$caseId/selfies'
    | '/api/public/v1/cases/$caseId/verification-sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/pricing'
    | '/_authenticated/onboarding'
    | '/invite/$token'
    | '/solutions/aml-screening'
    | '/solutions/business-verification'
    | '/solutions/fraud-risk'
    | '/solutions/person-verification'
    | '/verify/$token'
    | '/solutions/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/owner'
    | '/_authenticated/admin/plans'
    | '/_authenticated/console/alerts'
    | '/_authenticated/console/audit'
    | '/_authenticated/console/compliance'
    | '/_authenticated/console/go-live'
    | '/_authenticated/console/reports'
    | '/_authenticated/console/settings'
    | '/_authenticated/console/transactions'
    | '/_authenticated/console/watchlists'
    | '/_authenticated/admin/'
    | '/_authenticated/console/'
    | '/_authenticated/admin/companies/$orgId'
    | '/_authenticated/admin/invoices/$invoiceId'
    | '/_authenticated/console/cases/$caseId'
    | '/api/public/hooks/plaid-sync'
    | '/api/public/hooks/refresh-watchlists'
    | '/api/public/hooks/rescreen'
    | '/api/public/v1/alerts'
    | '/api/public/v1/cases'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/ping'
    | '/api/public/v1/reports'
    | '/api/public/v1/screening'
    | '/api/public/v1/transactions'
    | '/api/public/v1/alerts/$alertId'
    | '/api/public/v1/cases/$caseId'
    | '/api/public/v1/hits/$hitId'
    | '/api/public/v1/hosted/$token'
    | '/api/public/v1/reports/$reportId'
    | '/api/public/v1/cases/$caseId/addresses'
    | '/api/public/v1/cases/$caseId/bank'
    | '/api/public/v1/cases/$caseId/decision'
    | '/api/public/v1/cases/$caseId/documents'
    | '/api/public/v1/cases/$caseId/hits'
    | '/api/public/v1/cases/$caseId/owners'
    | '/api/public/v1/cases/$caseId/ownership'
    | '/api/public/v1/cases/$caseId/risk'
    | '/api/public/v1/cases/$caseId/screen'
    | '/api/public/v1/cases/$caseId/selfies'
    | '/api/public/v1/cases/$caseId/verification-sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SolutionsAmlScreeningRoute: typeof SolutionsAmlScreeningRoute
  SolutionsBusinessVerificationRoute: typeof SolutionsBusinessVerificationRoute
  SolutionsFraudRiskRoute: typeof SolutionsFraudRiskRoute
  SolutionsPersonVerificationRoute: typeof SolutionsPersonVerificationRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ApiPublicHooksPlaidSyncRoute: typeof ApiPublicHooksPlaidSyncRoute
  ApiPublicHooksRefreshWatchlistsRoute: typeof ApiPublicHooksRefreshWatchlistsRoute
  ApiPublicHooksRescreenRoute: typeof ApiPublicHooksRescreenRoute
  ApiPublicV1AlertsRoute: typeof ApiPublicV1AlertsRouteWithChildren
  ApiPublicV1CasesRoute: typeof ApiPublicV1CasesRouteWithChildren
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
  ApiPublicV1ReportsRoute: typeof ApiPublicV1ReportsRouteWithChildren
  ApiPublicV1ScreeningRoute: typeof ApiPublicV1ScreeningRoute
  ApiPublicV1TransactionsRoute: typeof ApiPublicV1TransactionsRoute
  ApiPublicV1HitsHitIdRoute: typeof ApiPublicV1HitsHitIdRoute
  ApiPublicV1HostedTokenRoute: typeof ApiPublicV1HostedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/aml-screening': {
      id: '/solutions/aml-screening'
      path: '/solutions/aml-screening'
      fullPath: '/solutions/aml-screening'
      preLoaderRoute: typeof SolutionsAmlScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/business-verification': {
      id: '/solutions/business-verification'
      path: '/solutions/business-verification'
      fullPath: '/solutions/business-verification'
      preLoaderRoute: typeof SolutionsBusinessVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/fraud-risk': {
      id: '/solutions/fraud-risk'
      path: '/solutions/fraud-risk'
      fullPath: '/solutions/fraud-risk'
      preLoaderRoute: typeof SolutionsFraudRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/person-verification': {
      id: '/solutions/person-verification'
      path: '/solutions/person-verification'
      fullPath: '/solutions/person-verification'
      preLoaderRoute: typeof SolutionsPersonVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/owner': {
      id: '/_authenticated/admin/owner'
      path: '/admin/owner'
      fullPath: '/admin/owner'
      preLoaderRoute: typeof AuthenticatedAdminOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/alerts': {
      id: '/_authenticated/console/alerts'
      path: '/console/alerts'
      fullPath: '/console/alerts'
      preLoaderRoute: typeof AuthenticatedConsoleAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/audit': {
      id: '/_authenticated/console/audit'
      path: '/console/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof AuthenticatedConsoleAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/compliance': {
      id: '/_authenticated/console/compliance'
      path: '/console/compliance'
      fullPath: '/console/compliance'
      preLoaderRoute: typeof AuthenticatedConsoleComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/go-live': {
      id: '/_authenticated/console/go-live'
      path: '/console/go-live'
      fullPath: '/console/go-live'
      preLoaderRoute: typeof AuthenticatedConsoleGoLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/reports': {
      id: '/_authenticated/console/reports'
      path: '/console/reports'
      fullPath: '/console/reports'
      preLoaderRoute: typeof AuthenticatedConsoleReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/console/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/transactions': {
      id: '/_authenticated/console/transactions'
      path: '/console/transactions'
      fullPath: '/console/transactions'
      preLoaderRoute: typeof AuthenticatedConsoleTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/watchlists': {
      id: '/_authenticated/console/watchlists'
      path: '/console/watchlists'
      fullPath: '/console/watchlists'
      preLoaderRoute: typeof AuthenticatedConsoleWatchlistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/companies/$orgId': {
      id: '/_authenticated/admin/companies/$orgId'
      path: '/admin/companies/$orgId'
      fullPath: '/admin/companies/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesOrgIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices/$invoiceId': {
      id: '/_authenticated/admin/invoices/$invoiceId'
      path: '/admin/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/cases/$caseId': {
      id: '/_authenticated/console/cases/$caseId'
      path: '/console/cases/$caseId'
      fullPath: '/console/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedConsoleCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/plaid-sync': {
      id: '/api/public/hooks/plaid-sync'
      path: '/api/public/hooks/plaid-sync'
      fullPath: '/api/public/hooks/plaid-sync'
      preLoaderRoute: typeof ApiPublicHooksPlaidSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-watchlists': {
      id: '/api/public/hooks/refresh-watchlists'
      path: '/api/public/hooks/refresh-watchlists'
      fullPath: '/api/public/hooks/refresh-watchlists'
      preLoaderRoute: typeof ApiPublicHooksRefreshWatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rescreen': {
      id: '/api/public/hooks/rescreen'
      path: '/api/public/hooks/rescreen'
      fullPath: '/api/public/hooks/rescreen'
      preLoaderRoute: typeof ApiPublicHooksRescreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/alerts': {
      id: '/api/public/v1/alerts'
      path: '/api/public/v1/alerts'
      fullPath: '/api/public/v1/alerts'
      preLoaderRoute: typeof ApiPublicV1AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/cases': {
      id: '/api/public/v1/cases'
      path: '/api/public/v1/cases'
      fullPath: '/api/public/v1/cases'
      preLoaderRoute: typeof ApiPublicV1CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/reports': {
      id: '/api/public/v1/reports'
      path: '/api/public/v1/reports'
      fullPath: '/api/public/v1/reports'
      preLoaderRoute: typeof ApiPublicV1ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/screening': {
      id: '/api/public/v1/screening'
      path: '/api/public/v1/screening'
      fullPath: '/api/public/v1/screening'
      preLoaderRoute: typeof ApiPublicV1ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/transactions': {
      id: '/api/public/v1/transactions'
      path: '/api/public/v1/transactions'
      fullPath: '/api/public/v1/transactions'
      preLoaderRoute: typeof ApiPublicV1TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/alerts/$alertId': {
      id: '/api/public/v1/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/api/public/v1/alerts/$alertId'
      preLoaderRoute: typeof ApiPublicV1AlertsAlertIdRouteImport
      parentRoute: typeof ApiPublicV1AlertsRoute
    }
    '/api/public/v1/cases/$caseId': {
      id: '/api/public/v1/cases/$caseId'
      path: '/$caseId'
      fullPath: '/api/public/v1/cases/$caseId'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdRouteImport
      parentRoute: typeof ApiPublicV1CasesRoute
    }
    '/api/public/v1/hits/$hitId': {
      id: '/api/public/v1/hits/$hitId'
      path: '/api/public/v1/hits/$hitId'
      fullPath: '/api/public/v1/hits/$hitId'
      preLoaderRoute: typeof ApiPublicV1HitsHitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/hosted/$token': {
      id: '/api/public/v1/hosted/$token'
      path: '/api/public/v1/hosted/$token'
      fullPath: '/api/public/v1/hosted/$token'
      preLoaderRoute: typeof ApiPublicV1HostedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/reports/$reportId': {
      id: '/api/public/v1/reports/$reportId'
      path: '/$reportId'
      fullPath: '/api/public/v1/reports/$reportId'
      preLoaderRoute: typeof ApiPublicV1ReportsReportIdRouteImport
      parentRoute: typeof ApiPublicV1ReportsRoute
    }
    '/api/public/v1/cases/$caseId/addresses': {
      id: '/api/public/v1/cases/$caseId/addresses'
      path: '/addresses'
      fullPath: '/api/public/v1/cases/$caseId/addresses'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdAddressesRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/bank': {
      id: '/api/public/v1/cases/$caseId/bank'
      path: '/bank'
      fullPath: '/api/public/v1/cases/$caseId/bank'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdBankRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/decision': {
      id: '/api/public/v1/cases/$caseId/decision'
      path: '/decision'
      fullPath: '/api/public/v1/cases/$caseId/decision'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdDecisionRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/documents': {
      id: '/api/public/v1/cases/$caseId/documents'
      path: '/documents'
      fullPath: '/api/public/v1/cases/$caseId/documents'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdDocumentsRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/hits': {
      id: '/api/public/v1/cases/$caseId/hits'
      path: '/hits'
      fullPath: '/api/public/v1/cases/$caseId/hits'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdHitsRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/owners': {
      id: '/api/public/v1/cases/$caseId/owners'
      path: '/owners'
      fullPath: '/api/public/v1/cases/$caseId/owners'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdOwnersRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/ownership': {
      id: '/api/public/v1/cases/$caseId/ownership'
      path: '/ownership'
      fullPath: '/api/public/v1/cases/$caseId/ownership'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdOwnershipRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/risk': {
      id: '/api/public/v1/cases/$caseId/risk'
      path: '/risk'
      fullPath: '/api/public/v1/cases/$caseId/risk'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdRiskRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/screen': {
      id: '/api/public/v1/cases/$caseId/screen'
      path: '/screen'
      fullPath: '/api/public/v1/cases/$caseId/screen'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdScreenRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/selfies': {
      id: '/api/public/v1/cases/$caseId/selfies'
      path: '/selfies'
      fullPath: '/api/public/v1/cases/$caseId/selfies'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdSelfiesRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
    '/api/public/v1/cases/$caseId/verification-sessions': {
      id: '/api/public/v1/cases/$caseId/verification-sessions'
      path: '/verification-sessions'
      fullPath: '/api/public/v1/cases/$caseId/verification-sessions'
      preLoaderRoute: typeof ApiPublicV1CasesCaseIdVerificationSessionsRouteImport
      parentRoute: typeof ApiPublicV1CasesCaseIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminOwnerRoute: typeof AuthenticatedAdminOwnerRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedConsoleAlertsRoute: typeof AuthenticatedConsoleAlertsRoute
  AuthenticatedConsoleAuditRoute: typeof AuthenticatedConsoleAuditRoute
  AuthenticatedConsoleComplianceRoute: typeof AuthenticatedConsoleComplianceRoute
  AuthenticatedConsoleGoLiveRoute: typeof AuthenticatedConsoleGoLiveRoute
  AuthenticatedConsoleReportsRoute: typeof AuthenticatedConsoleReportsRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleTransactionsRoute: typeof AuthenticatedConsoleTransactionsRoute
  AuthenticatedConsoleWatchlistsRoute: typeof AuthenticatedConsoleWatchlistsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedAdminCompaniesOrgIdRoute: typeof AuthenticatedAdminCompaniesOrgIdRoute
  AuthenticatedAdminInvoicesInvoiceIdRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  AuthenticatedConsoleCasesCaseIdRoute: typeof AuthenticatedConsoleCasesCaseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminOwnerRoute: AuthenticatedAdminOwnerRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedConsoleAlertsRoute: AuthenticatedConsoleAlertsRoute,
  AuthenticatedConsoleAuditRoute: AuthenticatedConsoleAuditRoute,
  AuthenticatedConsoleComplianceRoute: AuthenticatedConsoleComplianceRoute,
  AuthenticatedConsoleGoLiveRoute: AuthenticatedConsoleGoLiveRoute,
  AuthenticatedConsoleReportsRoute: AuthenticatedConsoleReportsRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleTransactionsRoute: AuthenticatedConsoleTransactionsRoute,
  AuthenticatedConsoleWatchlistsRoute: AuthenticatedConsoleWatchlistsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedAdminCompaniesOrgIdRoute: AuthenticatedAdminCompaniesOrgIdRoute,
  AuthenticatedAdminInvoicesInvoiceIdRoute:
    AuthenticatedAdminInvoicesInvoiceIdRoute,
  AuthenticatedConsoleCasesCaseIdRoute: AuthenticatedConsoleCasesCaseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1AlertsRouteChildren {
  ApiPublicV1AlertsAlertIdRoute: typeof ApiPublicV1AlertsAlertIdRoute
}

const ApiPublicV1AlertsRouteChildren: ApiPublicV1AlertsRouteChildren = {
  ApiPublicV1AlertsAlertIdRoute: ApiPublicV1AlertsAlertIdRoute,
}

const ApiPublicV1AlertsRouteWithChildren =
  ApiPublicV1AlertsRoute._addFileChildren(ApiPublicV1AlertsRouteChildren)

interface ApiPublicV1CasesCaseIdRouteChildren {
  ApiPublicV1CasesCaseIdAddressesRoute: typeof ApiPublicV1CasesCaseIdAddressesRoute
  ApiPublicV1CasesCaseIdBankRoute: typeof ApiPublicV1CasesCaseIdBankRoute
  ApiPublicV1CasesCaseIdDecisionRoute: typeof ApiPublicV1CasesCaseIdDecisionRoute
  ApiPublicV1CasesCaseIdDocumentsRoute: typeof ApiPublicV1CasesCaseIdDocumentsRoute
  ApiPublicV1CasesCaseIdHitsRoute: typeof ApiPublicV1CasesCaseIdHitsRoute
  ApiPublicV1CasesCaseIdOwnersRoute: typeof ApiPublicV1CasesCaseIdOwnersRoute
  ApiPublicV1CasesCaseIdOwnershipRoute: typeof ApiPublicV1CasesCaseIdOwnershipRoute
  ApiPublicV1CasesCaseIdRiskRoute: typeof ApiPublicV1CasesCaseIdRiskRoute
  ApiPublicV1CasesCaseIdScreenRoute: typeof ApiPublicV1CasesCaseIdScreenRoute
  ApiPublicV1CasesCaseIdSelfiesRoute: typeof ApiPublicV1CasesCaseIdSelfiesRoute
  ApiPublicV1CasesCaseIdVerificationSessionsRoute: typeof ApiPublicV1CasesCaseIdVerificationSessionsRoute
}

const ApiPublicV1CasesCaseIdRouteChildren: ApiPublicV1CasesCaseIdRouteChildren =
  {
    ApiPublicV1CasesCaseIdAddressesRoute: ApiPublicV1CasesCaseIdAddressesRoute,
    ApiPublicV1CasesCaseIdBankRoute: ApiPublicV1CasesCaseIdBankRoute,
    ApiPublicV1CasesCaseIdDecisionRoute: ApiPublicV1CasesCaseIdDecisionRoute,
    ApiPublicV1CasesCaseIdDocumentsRoute: ApiPublicV1CasesCaseIdDocumentsRoute,
    ApiPublicV1CasesCaseIdHitsRoute: ApiPublicV1CasesCaseIdHitsRoute,
    ApiPublicV1CasesCaseIdOwnersRoute: ApiPublicV1CasesCaseIdOwnersRoute,
    ApiPublicV1CasesCaseIdOwnershipRoute: ApiPublicV1CasesCaseIdOwnershipRoute,
    ApiPublicV1CasesCaseIdRiskRoute: ApiPublicV1CasesCaseIdRiskRoute,
    ApiPublicV1CasesCaseIdScreenRoute: ApiPublicV1CasesCaseIdScreenRoute,
    ApiPublicV1CasesCaseIdSelfiesRoute: ApiPublicV1CasesCaseIdSelfiesRoute,
    ApiPublicV1CasesCaseIdVerificationSessionsRoute:
      ApiPublicV1CasesCaseIdVerificationSessionsRoute,
  }

const ApiPublicV1CasesCaseIdRouteWithChildren =
  ApiPublicV1CasesCaseIdRoute._addFileChildren(
    ApiPublicV1CasesCaseIdRouteChildren,
  )

interface ApiPublicV1CasesRouteChildren {
  ApiPublicV1CasesCaseIdRoute: typeof ApiPublicV1CasesCaseIdRouteWithChildren
}

const ApiPublicV1CasesRouteChildren: ApiPublicV1CasesRouteChildren = {
  ApiPublicV1CasesCaseIdRoute: ApiPublicV1CasesCaseIdRouteWithChildren,
}

const ApiPublicV1CasesRouteWithChildren =
  ApiPublicV1CasesRoute._addFileChildren(ApiPublicV1CasesRouteChildren)

interface ApiPublicV1ReportsRouteChildren {
  ApiPublicV1ReportsReportIdRoute: typeof ApiPublicV1ReportsReportIdRoute
}

const ApiPublicV1ReportsRouteChildren: ApiPublicV1ReportsRouteChildren = {
  ApiPublicV1ReportsReportIdRoute: ApiPublicV1ReportsReportIdRoute,
}

const ApiPublicV1ReportsRouteWithChildren =
  ApiPublicV1ReportsRoute._addFileChildren(ApiPublicV1ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  InviteTokenRoute: InviteTokenRoute,
  SolutionsAmlScreeningRoute: SolutionsAmlScreeningRoute,
  SolutionsBusinessVerificationRoute: SolutionsBusinessVerificationRoute,
  SolutionsFraudRiskRoute: SolutionsFraudRiskRoute,
  SolutionsPersonVerificationRoute: SolutionsPersonVerificationRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ApiPublicHooksPlaidSyncRoute: ApiPublicHooksPlaidSyncRoute,
  ApiPublicHooksRefreshWatchlistsRoute: ApiPublicHooksRefreshWatchlistsRoute,
  ApiPublicHooksRescreenRoute: ApiPublicHooksRescreenRoute,
  ApiPublicV1AlertsRoute: ApiPublicV1AlertsRouteWithChildren,
  ApiPublicV1CasesRoute: ApiPublicV1CasesRouteWithChildren,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
  ApiPublicV1ReportsRoute: ApiPublicV1ReportsRouteWithChildren,
  ApiPublicV1ScreeningRoute: ApiPublicV1ScreeningRoute,
  ApiPublicV1TransactionsRoute: ApiPublicV1TransactionsRoute,
  ApiPublicV1HitsHitIdRoute: ApiPublicV1HitsHitIdRoute,
  ApiPublicV1HostedTokenRoute: ApiPublicV1HostedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
